BEGIN;

-- Konten awal dipindahkan dari data frontend agar PostgreSQL menjadi sumber data utama.
INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-led-tv-32-inch', 'JWS LED TV 32 Inch', 'Jam Waktu Sholat', 'Aplikasi jadwal sholat berbasis Android TV atau Google TV untuk masjid dan mushola.', 'JWS LED TV 32 Inch menampilkan jam, kalender, jadwal sholat, poster dakwah, video, dan informasi masjid melalui Android TV atau Google TV.', '32"', ARRAY['Android TV atau Google TV 32 inch', 'Lisensi aplikasi bergaransi', 'Menampilkan jam, kalender, jadwal sholat, poster dakwah, dan video', 'Cocok untuk mushola kantor atau masjid dengan jaringan internet', 'Setting menggunakan smartphone', 'Bonus desain poster dakwah dan video dakwah', 'Harga termasuk instalasi dan garansi lisensi aplikasi']::TEXT[], 3700000, NULL, 'https://youtu.be/m-ehFCc5G2g?si=O53EY5djuT2HssSs', TRUE, TRUE, 1)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-led-tv-32-inch');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-led-tv-32-inch'), 'Langsung instal tanpa STB', 3700000, 'Aplikasi jam sholat langsung dipasang di Google TV. Instalasi lebih sederhana dan harga lebih hemat.', 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-led-tv-32-inch'), 'Dengan STB', 4100000, 'Aplikasi dipasang di STB sehingga TV dapat dimatikan saat tidak digunakan, sementara aplikasi tetap berjalan.', 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('lisensi-key-activation-jws-android-tv', 'Lisensi Key Activation JWS Android TV', 'Lisensi Aplikasi', 'Lisensi aplikasi jam waktu sholat digital untuk Android TV atau Google TV yang sudah dimiliki customer.', 'Lisensi ini cocok jika Anda sudah memiliki Android TV atau Google TV dan ingin menggunakannya sebagai display jadwal waktu sholat digital.', NULL, ARRAY['Lisensi bergaransi dan berlaku seumur hidup', 'Dapat dipasang di berbagai ukuran LED TV mulai 24 inch hingga 48 inch', 'Resolusi HD', 'Dipandu cara setting hingga mahir', 'Bonus poster dakwah', 'Bonus video dakwah']::TEXT[], 1300000, NULL, NULL, FALSE, TRUE, 2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'lisensi-key-activation-jws-android-tv');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'lisensi-key-activation-jws-android-tv'), 'Lisensi Key Activation', 1300000, NULL, 1);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-rgb-2-panel-frame-figura-100x50', 'JWS RGB 2 Panel Frame Figura 100x50 cm', 'Jam Waktu Sholat', 'JWS full color dengan frame figura, poster masjid, dan setting via smartphone.', 'Produk JWS RGB 2 panel dengan frame figura dan poster masjid, cocok untuk masjid atau mushola yang membutuhkan tampilan jadwal sholat berwarna.', '100 x 50 cm', ARRAY['Frame figura ketebalan 4 cm', 'Terdapat poster masjid', '2 panel P5 RGB full color', 'Setting menggunakan smartphone Android', 'Akurasi tinggi dengan sistem GPS', 'Harga termasuk instalasi']::TEXT[], 1600000, NULL, 'https://youtu.be/gUXKX-79ysM?si=ERmTtl4WXUdGdZb3', TRUE, TRUE, 3)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-rgb-2-panel-frame-figura-100x50');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-rgb-2-panel-frame-figura-100x50'), 'Versi biasa', 1600000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-rgb-2-panel-frame-figura-100x50'), 'Versi auto murotal', 1900000, NULL, 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-2-panel-rgb-frame-aluminium', 'JWS 2 Panel RGB Frame Aluminium', 'Jam Waktu Sholat', 'JWS RGB ukuran ringkas dengan frame aluminium hollow dan akurasi GPS.', 'JWS 2 panel RGB frame aluminium cocok untuk kebutuhan display jadwal sholat berwarna dengan ukuran lebih ringkas.', '70 x 20 cm', ARRAY['Frame aluminium hollow 2 x 1 inch', '2 panel P5 RGB full color', 'Setting menggunakan smartphone Android', 'Akurasi tinggi menggunakan GPS', 'Harga termasuk instalasi']::TEXT[], 1200000, NULL, 'https://youtu.be/DCAdNNyZtwE?si=k_Mh2dey1xET9JPh', FALSE, TRUE, 4)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-2-panel-rgb-frame-aluminium');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-2-panel-rgb-frame-aluminium'), 'Versi biasa', 1200000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-2-panel-rgb-frame-aluminium'), 'Versi auto murotal', 1500000, NULL, 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-1-warna-2-panel-frame-figura', 'JWS 1 Warna 2 Panel Frame Figura', 'Jam Waktu Sholat', 'JWS single color dengan frame figura dan poster masjid.', 'Produk JWS 1 warna 2 panel menggunakan panel P10 single color, frame figura, dan poster masjid untuk tampilan yang rapi.', '100 x 50 cm', ARRAY['Frame figura ketebalan 4 cm', 'Terdapat poster masjid', '2 panel P10 single color', 'Setting menggunakan smartphone', 'Akurasi tinggi dengan GPS', 'Harga termasuk instalasi']::TEXT[], 1400000, NULL, 'https://youtu.be/ZqU8wKnDF8E?si=RFN6kqsbH4MLcEq8', FALSE, TRUE, 5)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-1-warna-2-panel-frame-figura');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-1-warna-2-panel-frame-figura'), 'Versi biasa', 1400000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-1-warna-2-panel-frame-figura'), 'Versi auto murotal', 1700000, NULL, 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-p10-3-panel-satu-warna-frame-aluminium', 'JWS P10 3 Panel Satu Warna Frame Aluminium', 'Jam Waktu Sholat', 'JWS single color 3 panel P10 dengan frame aluminium hollow.', 'JWS P10 3 panel satu warna menggunakan frame aluminium hollow dan cocok untuk tampilan jadwal sholat sederhana.', '100 x 20 cm', ARRAY['Frame aluminium hollow 2 x 1 inch', '3 panel P10 single color', 'Setting menggunakan smartphone', 'Akurasi tinggi dengan GPS', 'Harga termasuk instalasi']::TEXT[], 1200000, NULL, 'https://youtu.be/HnENfj7EnPI?si=ditWTb_-AZd8a3Vu', FALSE, TRUE, 6)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-p10-3-panel-satu-warna-frame-aluminium');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-p10-3-panel-satu-warna-frame-aluminium'), 'Versi biasa', 1200000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-p10-3-panel-satu-warna-frame-aluminium'), 'Versi auto murotal', 1500000, NULL, 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jam-digital-2-panel', 'Jam Digital 2 Panel', 'Jam Digital', 'Jam digital 2 panel P10 single color tanpa jadwal sholat.', 'Jam Digital 2 Panel menampilkan jam dan tanggal saja, cocok untuk kebutuhan display waktu sederhana tanpa jadwal sholat.', '70 x 20 cm', ARRAY['2 panel P10 single color', 'Frame aluminium hollow 2 x 1 inch', 'Menampilkan jam dan tanggal', 'Setting menggunakan smartphone', 'Lebih akurat dengan GPS', 'Harga termasuk instalasi']::TEXT[], 700000, NULL, 'https://youtu.be/bBZa7e-95KE?si=MCVVI-wz6Q7N0zbb', FALSE, TRUE, 7)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jam-digital-2-panel');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jam-digital-2-panel'), 'Jam digital 2 panel', 700000, NULL, 1);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-p10-rgb-3-panel-frame-aluminium', 'JWS P10 RGB 3 Panel Frame Aluminium', 'Jam Waktu Sholat', 'JWS RGB 3 panel untuk jam, tanggal, jadwal sholat, dan running text.', 'JWS P10 RGB 3 Panel Frame Aluminium menampilkan jam, tanggal, jadwal sholat, dan teks berjalan dengan panel RGB.', '100 x 20 cm', ARRAY['3 panel P10 1/8S RGB atau 3 panel P5 RGB', 'Frame aluminium hollow 2 x 1 inch', 'Menampilkan jam, tanggal, jadwal sholat, dan teks berjalan', 'Setting menggunakan smartphone', 'Lebih akurat dengan GPS', 'Harga termasuk instalasi']::TEXT[], 1500000, NULL, 'https://youtu.be/wikLYIN4B_8?si=t924sFD-km0oX0CJ', TRUE, TRUE, 8)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-p10-rgb-3-panel-frame-aluminium');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-p10-rgb-3-panel-frame-aluminium'), 'Versi biasa', 1500000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-p10-rgb-3-panel-frame-aluminium'), 'Versi auto murotal', 1800000, NULL, 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-rgb-5-panel-frame-aluminium', 'JWS RGB 5 Panel Frame Aluminium', 'Jam Waktu Sholat', 'JWS RGB 5 panel dengan frame aluminium untuk display lebih panjang.', 'JWS RGB 5 Panel Frame Aluminium cocok untuk masjid yang membutuhkan area teks berjalan lebih panjang.', '165 x 20 cm', ARRAY['5 panel P10 1/8S RGB atau 3 panel P5 RGB', 'Frame aluminium hollow 2 x 1 inch', 'Menampilkan jam, tanggal, jadwal sholat, dan teks berjalan', 'Setting menggunakan smartphone', 'Lebih akurat dengan GPS', 'Harga termasuk instalasi']::TEXT[], 1900000, NULL, 'https://youtu.be/NTV0IuyhrS4?si=1DS7izCQy7-ASMmy', FALSE, TRUE, 9)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-rgb-5-panel-frame-aluminium');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-rgb-5-panel-frame-aluminium'), 'JWS RGB 5 panel', 1900000, NULL, 1);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-rgb-10-panel-2-baris', 'JWS RGB 10 Panel 2 Baris', 'Jam Waktu Sholat', 'JWS RGB 10 panel dua baris untuk tampilan informasi lebih besar.', 'JWS RGB 10 Panel 2 Baris menyediakan area display lebih besar untuk jam, tanggal, jadwal sholat, dan teks berjalan.', '165 x 35 cm', ARRAY['10 panel P10 1/8S RGB atau 3 panel P5 RGB', 'Frame aluminium hollow 2 x 1 inch', 'Menampilkan jam, tanggal, jadwal sholat, dan teks berjalan', 'Setting menggunakan smartphone', 'Lebih akurat dengan GPS', 'Harga termasuk instalasi']::TEXT[], 3100000, NULL, 'https://youtu.be/hgs_jxV4ww8?si=_XUCTVqC6jyY6MjE', FALSE, TRUE, 10)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-rgb-10-panel-2-baris');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-rgb-10-panel-2-baris'), 'JWS RGB 10 panel 2 baris', 3100000, NULL, 1);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-seven-segment-1-05-tanpa-running-text', 'JWS Seven Segment 1" & 0,5" Tanpa Running Text', 'Seven Segment', 'JWS seven segment dengan ukuran jam 1 inch dan jadwal sholat 0,5 inch tanpa running text.', 'JWS Seven Segment 1 inch dan 0,5 inch tanpa running text cocok untuk masjid atau mushola yang membutuhkan tampilan jadwal sholat klasik.', '80 x 40 cm', ARRAY['Frame figura ketebalan 4 cm', 'Ukuran jam 1 inch', 'Ukuran kalender dan jadwal sholat 0,5 inch', 'Poster masjid dilengkapi lampu belakang', 'Kaca akrilik lebih ringan dan aman', 'Setting menggunakan smartphone', 'Lebih akurat dengan GPS', 'Harga termasuk instalasi']::TEXT[], 2200000, NULL, 'https://youtu.be/8CT8CaSOIhs?si=VBCV96pAIpquB1-L', FALSE, TRUE, 11)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-seven-segment-1-05-tanpa-running-text');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-seven-segment-1-05-tanpa-running-text'), 'Tanpa running text', 2200000, NULL, 1);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-seven-segment-1-08-running-text', 'JWS Seven Segment 1" & 0,8" Dilengkapi Running Text', 'Seven Segment', 'JWS seven segment dengan running text 2 panel P4.75 single color.', 'JWS Seven Segment 1 inch dan 0,8 inch dilengkapi running text, poster masjid, dan akurasi GPS.', '100 x 50 cm', ARRAY['Frame figura ketebalan 4 cm', 'Ukuran jam 1 inch', 'Ukuran kalender dan jadwal sholat 0,8 inch', 'Running text 2 panel P4.75 single color', 'Poster masjid dilengkapi lampu belakang', 'Kaca akrilik lebih ringan dan lebih kuat', 'Setting menggunakan smartphone', 'Akurasi tinggi dengan GPS', 'Harga termasuk instalasi']::TEXT[], 2600000, NULL, 'https://youtu.be/dFiEdeY_y7E?si=N8Y27wyYmsRW66DN', FALSE, TRUE, 12)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-seven-segment-1-08-running-text');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-seven-segment-1-08-running-text'), 'Versi biasa', 2600000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-seven-segment-1-08-running-text'), 'Versi auto murotal', 2900000, NULL, 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-seven-segment-25-1-tanpa-running-text', 'JWS Seven Segment 2,5" & 1" Tanpa Running Text', 'Seven Segment', 'JWS seven segment ukuran besar tanpa running text dengan poster masjid.', 'JWS Seven Segment 2,5 inch dan 1 inch tanpa running text dibuat untuk visibilitas lebih tinggi dengan frame figura.', '120 x 60 cm', ARRAY['Frame figura ketebalan 4 cm', 'Ukuran jam 2,5 inch', 'Ukuran kalender dan jadwal sholat 1 inch', 'Poster masjid dilengkapi lampu belakang', 'Kaca akrilik lebih ringan dan aman', 'Setting menggunakan smartphone', 'Lebih akurat dengan GPS', 'Harga termasuk instalasi']::TEXT[], 3000000, NULL, 'https://youtu.be/NdlzlH1CB6I?si=bflFiC_COo7M5jPU', FALSE, TRUE, 13)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-seven-segment-25-1-tanpa-running-text');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-seven-segment-25-1-tanpa-running-text'), 'Versi biasa', 3000000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-seven-segment-25-1-tanpa-running-text'), 'Versi auto murotal', 3300000, NULL, 2);

INSERT INTO products (slug, name, category, short_description, description, dimensions, features, price_start_from, image_url, video_url, is_featured, is_active, order_index)
VALUES ('jws-seven-segment-jumbo-25-1-running-text', 'JWS Seven Segment Jumbo 2,5" & 1" Dilengkapi Running Text', 'Seven Segment', 'JWS seven segment jumbo dengan running text dan kaca akrilik anti pecah.', 'JWS Seven Segment Jumbo dilengkapi running text 2 panel P4.75 single color, poster masjid, dan akurasi GPS.', '120 x 60 cm', ARRAY['Frame figura ketebalan 4 cm lapis', 'Ukuran jam 2,5 inch', 'Ukuran kalender dan jadwal sholat 1 inch', 'Running text 2 panel P4.75 single color', 'Terdapat poster masjid', 'Kaca akrilik anti pecah', 'Setting menggunakan smartphone', 'Akurasi tinggi dengan GPS', 'Harga termasuk instalasi']::TEXT[], 3400000, NULL, 'https://youtu.be/KqT8KIg_4hM?si=snUdf-ZjijpsWUv9', TRUE, TRUE, 14)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, short_description = EXCLUDED.short_description, description = EXCLUDED.description, dimensions = EXCLUDED.dimensions, features = EXCLUDED.features, price_start_from = EXCLUDED.price_start_from, image_url = EXCLUDED.image_url, video_url = EXCLUDED.video_url, is_featured = EXCLUDED.is_featured, order_index = EXCLUDED.order_index;
DELETE FROM product_variants WHERE product_id = (SELECT id FROM products WHERE slug = 'jws-seven-segment-jumbo-25-1-running-text');
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-seven-segment-jumbo-25-1-running-text'), 'Versi biasa', 3400000, NULL, 1);
INSERT INTO product_variants (product_id, name, price, description, order_index) VALUES ((SELECT id FROM products WHERE slug = 'jws-seven-segment-jumbo-25-1-running-text'), 'Versi auto murotal', 3700000, NULL, 2);

INSERT INTO testimonials (title, description, image_alt, rating, is_active, order_index)
SELECT 'Pemasangan JWS Digital', 'Dokumentasi produk setelah terpasang dan aktif di lokasi.', 'Placeholder foto pemasangan JWS Digital', 5, TRUE, 1
WHERE NOT EXISTS (SELECT 1 FROM testimonials WHERE title = 'Pemasangan JWS Digital');
INSERT INTO testimonials (title, description, image_alt, rating, is_active, order_index)
SELECT 'Panel Running Text', 'Dokumentasi tampilan running text sesuai kebutuhan pelanggan.', 'Placeholder foto panel running text', 5, TRUE, 2
WHERE NOT EXISTS (SELECT 1 FROM testimonials WHERE title = 'Panel Running Text');
INSERT INTO testimonials (title, description, image_alt, rating, is_active, order_index)
SELECT 'Pengaturan Perangkat', 'Dokumentasi proses aktivasi dan pengaturan perangkat.', 'Placeholder foto pengaturan perangkat JWS', 5, TRUE, 3
WHERE NOT EXISTS (SELECT 1 FROM testimonials WHERE title = 'Pengaturan Perangkat');

INSERT INTO tutorials (slug, title, category, short_description, video_url, is_active, order_index)
VALUES ('setting-jam-waktu-sholat', 'Cara Setting Jam Waktu Sholat', 'Jam Waktu Sholat', 'Langkah dasar untuk menghubungkan perangkat dan membuka menu setting jam waktu sholat digital.', 'https://youtu.be/Z7R_cdpNdpQ?si=RjrdDJPy3dKollhf', TRUE, 1)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, short_description = EXCLUDED.short_description, video_url = EXCLUDED.video_url, order_index = EXCLUDED.order_index;
DELETE FROM tutorial_steps WHERE tutorial_id = (SELECT id FROM tutorials WHERE slug = 'setting-jam-waktu-sholat');
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-jam-waktu-sholat'), 1, 'Hidupkan WiFi', 'Pastikan WiFi di smartphone atau komputer sudah menyala.', NULL);
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-jam-waktu-sholat'), 2, 'Hubungkan ke WiFi JWS', 'Cari dan hubungkan perangkat ke jaringan WiFi jam waktu sholat.', NULL);
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-jam-waktu-sholat'), 3, 'Masukkan Password', 'Gunakan password standar perangkat.', 'unaproject28');
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-jam-waktu-sholat'), 4, 'Akses Menu Setting', 'Buka browser dan masuk ke menu pengaturan jam waktu sholat.', NULL);
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-jam-waktu-sholat'), 5, 'Atur Parameter', 'Sesuaikan parameter seperti kota, zona waktu, iqomah, dan pengaturan lain sesuai kebutuhan.', NULL);

INSERT INTO tutorials (slug, title, category, short_description, video_url, is_active, order_index)
VALUES ('setting-running-text-jws', 'Cara Setting Running Text JWS', 'Running Text LED', 'Panduan dasar untuk menghubungkan running text dan mengatur teks yang akan ditampilkan.', 'https://youtu.be/muEazVfsELg?si=4kfd_nNxw4vKHiMs', TRUE, 2)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, short_description = EXCLUDED.short_description, video_url = EXCLUDED.video_url, order_index = EXCLUDED.order_index;
DELETE FROM tutorial_steps WHERE tutorial_id = (SELECT id FROM tutorials WHERE slug = 'setting-running-text-jws');
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-running-text-jws'), 1, 'Download Aplikasi', 'Download aplikasi LedART melalui Google Play Store.', NULL);
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-running-text-jws'), 2, 'Hubungkan WiFi', 'Hubungkan perangkat ke WiFi running text. Biasanya diawali dengan nama jaringan HD_W02.', NULL);
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-running-text-jws'), 3, 'Masukkan Password', 'Gunakan password running text.', 'unaproject28');
INSERT INTO tutorial_steps (tutorial_id, step_number, title, description, highlight) VALUES ((SELECT id FROM tutorials WHERE slug = 'setting-running-text-jws'), 4, 'Konfigurasi Text', 'Setelah terhubung, mulai atur teks yang akan ditampilkan pada panel running text.', NULL);

DELETE FROM order_steps;
INSERT INTO order_steps (step_number, title, description, icon_name, is_active, order_index) VALUES ('01', 'Pilih Produk', 'Lihat katalog produk dan tentukan jenis kebutuhan awal, misalnya jam waktu sholat, running text LED, atau produk custom.', 'default', TRUE, 1);
INSERT INTO order_steps (step_number, title, description, icon_name, is_active, order_index) VALUES ('02', 'Konsultasi Kebutuhan', 'Diskusikan lokasi pemasangan, ukuran, fitur, warna tampilan, serta kebutuhan informasi yang ingin ditampilkan.', 'default', TRUE, 2);
INSERT INTO order_steps (step_number, title, description, icon_name, is_active, order_index) VALUES ('03', 'Konfirmasi Ukuran dan Harga', 'UNA Project membantu menghitung estimasi harga berdasarkan ukuran, bahan, fitur, dan kebutuhan pemasangan.', 'default', TRUE, 3);
INSERT INTO order_steps (step_number, title, description, icon_name, is_active, order_index) VALUES ('04', 'Pembayaran DP', 'Setelah spesifikasi disepakati, customer melakukan pembayaran DP sebagai tanda mulai proses produksi.', 'default', TRUE, 4);
INSERT INTO order_steps (step_number, title, description, icon_name, is_active, order_index) VALUES ('05', 'Proses Produksi', 'Produk dibuat sesuai spesifikasi yang sudah disepakati. Lama produksi menyesuaikan tingkat custom dan antrean pekerjaan.', 'default', TRUE, 5);
INSERT INTO order_steps (step_number, title, description, icon_name, is_active, order_index) VALUES ('06', 'Instalasi atau Pengiriman', 'Produk dikirim atau dipasang sesuai kesepakatan. Untuk produk tertentu, proses setting awal dapat dibantu.', 'default', TRUE, 6);
INSERT INTO order_steps (step_number, title, description, icon_name, is_active, order_index) VALUES ('07', 'Garansi dan After-Sales', 'Setelah produk diterima, customer tetap bisa berkonsultasi untuk penggunaan, setting, dan kendala dasar.', 'default', TRUE, 7);

UPDATE whatsapp_templates SET is_default = FALSE WHERE category IN ('Konsultasi', 'Produk', 'Dukungan');
INSERT INTO whatsapp_templates (template_name, category, message_pattern, is_default, is_active) VALUES ('konsultasi_umum', 'Konsultasi', 'Halo UNA Project, saya ingin konsultasi produk UNA Project.', TRUE, TRUE) ON CONFLICT (template_name) DO UPDATE SET category = EXCLUDED.category, message_pattern = EXCLUDED.message_pattern, is_default = EXCLUDED.is_default, is_active = EXCLUDED.is_active;
INSERT INTO whatsapp_templates (template_name, category, message_pattern, is_default, is_active) VALUES ('konsultasi_produk', 'Produk', 'Halo UNA Project, saya ingin konsultasi produk {product_name}.', TRUE, TRUE) ON CONFLICT (template_name) DO UPDATE SET category = EXCLUDED.category, message_pattern = EXCLUDED.message_pattern, is_default = EXCLUDED.is_default, is_active = EXCLUDED.is_active;
INSERT INTO whatsapp_templates (template_name, category, message_pattern, is_default, is_active) VALUES ('info_garansi', 'Dukungan', 'Halo UNA Project, saya ingin tanya garansi produk.', TRUE, TRUE) ON CONFLICT (template_name) DO UPDATE SET category = EXCLUDED.category, message_pattern = EXCLUDED.message_pattern, is_default = EXCLUDED.is_default, is_active = EXCLUDED.is_active;

COMMIT;
